apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: backend
          image: <kltod>/notes-backend:v1
          env:
            - name: DATABASE_HOST
              value: "notes-db"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "notesdb"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend
spec:
  type: ClusterIP
  selector:
    app: notes-backend
  ports:
    - port: 5001
      targetPort: 5001
